import type { Metadata } from "next";
import { DMSans } from "@/config/fonts";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.className} `}>
        <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </body>
    </html>
  );
}
